---
layout: post
title: django 1.7 > 1.11 migrate gets error “table already exists”
date:   2018-03-14
description: > 
  Most of the time when you are building something you will always come across bugs and issues that could make you try to figure out what could be the problem. This always consumes time you could find 
  yourself fixed at a bug that can consume your time. Apparently I have come across such challenges one of them is this kind of migration error below which I thought it would be nic to share.

keywords: "django,gh-pages,website,blog,easy"
categories: [Django,Blog,Python]
tags: [django,blog,tutorial,python]
icon: icon-html
author: author1


---
Most of the time when you are building something you will always come across bugs and issues that could make you try to figure out what could be the problem. This always consumes time you could find 
yourself fixed at a bug that can consume your time. Apparently I have come across such challenges one of them is this kind of migration error below which I thought it would be nic to share.

# Problem

You are trying to apply a migration but am getting the error:

```bash
django.db.utils.OperationalError: (1050, "Table 'customers_customer' already exists")
```

# Solution 

If you have the table created in the database, you can run

```bash
python manage.py migrate --fake <appname>
```

__Mark migrations as run without actually running them__

Or if you want to avoid some actions in your migration, you can edit the migration file under the app/migrations directory and comment the operations you don't want to do in the migrate execution.

